### PR TITLE
Add server 6.6 configuration

### LINKED ISSUE #53: Build 6.6 kernel for server on noble
Refs https://github.com/freedomofpress/securedrop/issues/7210

noble ships with Linux 6.8, let's see if we can get a 6.6 grsec patched version working. That would be ideal since we can stay in sync with the workstation too. If that doesn't work, a short-term patch for 6.8 is available, as well as beta for 6.10.

### PR DESCRIPTION
**Pull request by legoktm**
Generated roughly the same as 4f7504afb354, by taking the 5.15 config and running `make olddefconfig` with a grsec-patched 6.6.57 kernel in a bookworm container.

Fixes #53.

### CODE REVIEW

**Comment by legoktm** [comment]
Probably ready for review, let me actually build and try the kernels on noble before we merge this.

**Comment by legoktm** [comment]
This is ready to be reviewed/land now, I built a kernel using this (see https://github.com/freedomofpress/securedrop-apt-test/pull/249) and it booted on a NUC 10 running noble.

**Comment by legoktm** [comment]
Missing some nftables modules:
```
$ rg -i nf_table config-securedrop-6.6
1246:CONFIG_NF_TABLES=m
1247:# CONFIG_NF_TABLES_INET is not set
1248:# CONFIG_NF_TABLES_NETDEV is not set
1435:# CONFIG_NF_TABLES_IPV4 is not set
1436:# CONFIG_NF_TABLES_ARP is not set
1471:# CONFIG_NF_TABLES_IPV6 is not set
1499:CONFIG_NF_TABLES_BRIDGE=m
```

**Review by zenmonkeykstop — APPROVED** [review]
Visual review (focused on nftables and grsec sections only) seems good. Approving.

**Pull request merged**
